// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using avarice_backend;

#nullable disable

namespace avarice_backend.Migrations
{
    [DbContext(typeof(AvariceContext))]
    [Migration("20221003200356_Fixes")]
    partial class Fixes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "latin1");

            modelBuilder.Entity("avarice_backend.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("currency")
                        .HasDefaultValueSql("'HRK'");

                    b.Property<double>("InitialBalance")
                        .HasColumnType("double")
                        .HasColumnName("initialBalance");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "userId");

                    b.ToTable("account", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "latin1");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "latin1_swedish_ci");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Currency = "HRK",
                            InitialBalance = 14000.0,
                            Name = "Gyro",
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 2L,
                            Currency = "EUR",
                            InitialBalance = 200.0,
                            Name = "Euros",
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 3L,
                            Currency = "HRK",
                            InitialBalance = 0.0,
                            Name = "Checking",
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 4L,
                            Currency = "HRK",
                            InitialBalance = 800.0,
                            Name = "Pocket",
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        });
                });

            modelBuilder.Entity("avarice_backend.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("color");

                    b.Property<string>("Icon")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parentId");

                    b.Property<ulong>("System")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(0ul)
                        .HasColumnName("system");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("UserId");

                    b.ToTable("category", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "latin1");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "latin1_swedish_ci");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Color = "grey",
                            Icon = "mdi-swap-horizontal",
                            Name = "Transfer",
                            System = 1ul
                        },
                        new
                        {
                            Id = 2L,
                            Color = "#ffffff",
                            Icon = "mdi-food-fork-drink",
                            Name = "Food & Drinks",
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 3L,
                            Color = "#ffffff",
                            Icon = "mdi-food",
                            Name = "Restaurant, fast-food",
                            ParentId = 2L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 4L,
                            Color = "#ffffff",
                            Icon = "mdi-glass-cocktail",
                            Name = "Bar, cafe",
                            ParentId = 2L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 5L,
                            Color = "#ffffff",
                            Icon = "mdi-cart",
                            Name = "Groceries",
                            ParentId = 2L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 6L,
                            Color = "#ffffff",
                            Icon = "mdi-basket",
                            Name = "Shopping",
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 7L,
                            Color = "#ffffff",
                            Icon = "mdi-tshirt-crew",
                            Name = "Clothes and shoes",
                            ParentId = 6L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 8L,
                            Color = "#ffffff",
                            Icon = "mdi-pill",
                            Name = "Drug-store, chemist",
                            ParentId = 6L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 9L,
                            Color = "#ffffff",
                            Icon = "mdi-laptop",
                            Name = "Electronics, accessories",
                            ParentId = 6L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 10L,
                            Color = "#ffffff",
                            Icon = "mdi-emoticon",
                            Name = "Free time",
                            ParentId = 6L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 11L,
                            Color = "#ffffff",
                            Icon = "mdi-gift",
                            Name = "Gifts, joy",
                            ParentId = 6L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 12L,
                            Color = "#ffffff",
                            Icon = "mdi-bottle-tonic-plus",
                            Name = "Health and beauty",
                            ParentId = 6L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 13L,
                            Color = "#ffffff",
                            Icon = "mdi-home",
                            Name = "Home, garden",
                            ParentId = 6L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 14L,
                            Color = "#ffffff",
                            Icon = "mdi-diamond-stone",
                            Name = "Jewels, accessories",
                            ParentId = 6L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 15L,
                            Color = "#ffffff",
                            Icon = "mdi-baby-carriage",
                            Name = "Kids",
                            ParentId = 6L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 16L,
                            Color = "#ffffff",
                            Icon = "mdi-paw",
                            Name = "Pets, animals",
                            ParentId = 6L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 17L,
                            Color = "#ffffff",
                            Icon = "mdi-hammer-screwdriver",
                            Name = "Stationery, tools",
                            ParentId = 6L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 18L,
                            Color = "#ffffff",
                            Icon = "mdi-home",
                            Name = "Housing",
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 19L,
                            Color = "#ffffff",
                            Icon = "mdi-lightbulb",
                            Name = "Energy, utilities",
                            ParentId = 18L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 20L,
                            Color = "#ffffff",
                            Icon = "mdi-hammer",
                            Name = "Maintenance, repairs",
                            ParentId = 18L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 21L,
                            Color = "#ffffff",
                            Icon = "mdi-bank-plus",
                            Name = "Mortgage",
                            ParentId = 18L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 22L,
                            Color = "#ffffff",
                            Icon = "mdi-shield-home",
                            Name = "Property insurance",
                            ParentId = 18L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 23L,
                            Color = "#ffffff",
                            Icon = "mdi-key-variant",
                            Name = "Rent",
                            ParentId = 18L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 24L,
                            Color = "#ffffff",
                            Icon = "mdi-home-circle-outline",
                            Name = "Services",
                            ParentId = 18L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 25L,
                            Color = "#ffffff",
                            Icon = "mdi-bus",
                            Name = "Transportation",
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 26L,
                            Color = "#ffffff",
                            Icon = "mdi-bag-suitcase",
                            Name = "Business trips",
                            ParentId = 25L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 27L,
                            Color = "#ffffff",
                            Icon = "mdi-airplane",
                            Name = "Long distance",
                            ParentId = 25L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 28L,
                            Color = "#ffffff",
                            Icon = "mdi-tram",
                            Name = "Public transport",
                            ParentId = 25L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 29L,
                            Color = "#ffffff",
                            Icon = "mdi-taxi",
                            Name = "Taxi",
                            ParentId = 25L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 30L,
                            Color = "#ffffff",
                            Icon = "mdi-car",
                            Name = "Vehicle",
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 31L,
                            Color = "#ffffff",
                            Icon = "mdi-fuel",
                            Name = "Fuel",
                            ParentId = 30L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 32L,
                            Color = "#ffffff",
                            Icon = "mdi-car",
                            Name = "Leasing",
                            ParentId = 30L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 33L,
                            Color = "#ffffff",
                            Icon = "mdi-parking",
                            Name = "Parking",
                            ParentId = 30L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 34L,
                            Color = "#ffffff",
                            Icon = "mdi-key",
                            Name = "Rentals",
                            ParentId = 30L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 35L,
                            Color = "#ffffff",
                            Icon = "mdi-shield-car",
                            Name = "Vehicle insurance",
                            ParentId = 30L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 36L,
                            Color = "#ffffff",
                            Icon = "mdi-tools",
                            Name = "Vehicle maintenance",
                            ParentId = 30L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 37L,
                            Color = "#ffffff",
                            Icon = "mdi-account",
                            Name = "Life & Entertainment",
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 38L,
                            Color = "#ffffff",
                            Icon = "mdi-dumbbell",
                            Name = "Active sport, fitness",
                            ParentId = 37L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 39L,
                            Color = "#ffffff",
                            Icon = "mdi-cup",
                            Name = "Alcohol, tobacco",
                            ParentId = 37L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 40L,
                            Color = "#ffffff",
                            Icon = "mdi-book-open-variant",
                            Name = "Books, audio, subscriptions",
                            ParentId = 37L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 41L,
                            Color = "#ffffff",
                            Icon = "mdi-gift",
                            Name = "Charity, gifts",
                            ParentId = 37L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 42L,
                            Color = "#ffffff",
                            Icon = "mdi-drama-masks",
                            Name = "Culture, sports events",
                            ParentId = 37L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 43L,
                            Color = "#ffffff",
                            Icon = "mdi-school",
                            Name = "Education, development",
                            ParentId = 37L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 44L,
                            Color = "#ffffff",
                            Icon = "mdi-doctor",
                            Name = "Health care, doctor",
                            ParentId = 37L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 45L,
                            Color = "#ffffff",
                            Icon = "mdi-heart",
                            Name = "Hobbies",
                            ParentId = 37L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 46L,
                            Color = "#ffffff",
                            Icon = "mdi-palm-tree",
                            Name = "Holiday, trips, hotels",
                            ParentId = 37L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 47L,
                            Color = "#ffffff",
                            Icon = "mdi-cake",
                            Name = "Life events",
                            ParentId = 37L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 48L,
                            Color = "#ffffff",
                            Icon = "mdi-dice-5",
                            Name = "Lottery, gambling",
                            ParentId = 37L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 49L,
                            Color = "#ffffff",
                            Icon = "mdi-television-classic",
                            Name = "TV, Streaming",
                            ParentId = 37L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 50L,
                            Color = "#ffffff",
                            Icon = "mdi-flower",
                            Name = "Wellness, beauty",
                            ParentId = 37L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 51L,
                            Color = "#ffffff",
                            Icon = "mdi-basketball",
                            Name = "Culture, sport events",
                            ParentId = 37L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 52L,
                            Color = "#ffffff",
                            Icon = "mdi-laptop",
                            Name = "Communication, PC",
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 53L,
                            Color = "#ffffff",
                            Icon = "mdi-wifi",
                            Name = "Internet",
                            ParentId = 52L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 54L,
                            Color = "#ffffff",
                            Icon = "mdi-phone",
                            Name = "Phone, cell phone",
                            ParentId = 52L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 55L,
                            Color = "#ffffff",
                            Icon = "mdi-email",
                            Name = "Postal services",
                            ParentId = 52L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 56L,
                            Color = "#ffffff",
                            Icon = "mdi-controller-classic",
                            Name = "Software, apps, games",
                            ParentId = 52L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 57L,
                            Color = "#ffffff",
                            Icon = "mdi-controller-classic",
                            Name = "Games",
                            ParentId = 52L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 58L,
                            Color = "#ffffff",
                            Icon = "mdi-currency-usd",
                            Name = "Financial expenses",
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 59L,
                            Color = "#ffffff",
                            Icon = "mdi-account-alert",
                            Name = "Advisory",
                            ParentId = 58L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 60L,
                            Color = "#ffffff",
                            Icon = "mdi-comment-remove",
                            Name = "Charges, Fees",
                            ParentId = 58L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 61L,
                            Color = "#ffffff",
                            Icon = "mdi-account-child",
                            Name = "Child Support",
                            ParentId = 58L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 62L,
                            Color = "#ffffff",
                            Icon = "mdi-alert-circle",
                            Name = "Fines",
                            ParentId = 58L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 63L,
                            Color = "#ffffff",
                            Icon = "mdi-card-bulleted",
                            Name = "Insurances",
                            ParentId = 58L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 64L,
                            Color = "#ffffff",
                            Icon = "mdi-cards",
                            Name = "Loan, interests",
                            ParentId = 58L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 65L,
                            Color = "#ffffff",
                            Icon = "mdi-content-cut",
                            Name = "Taxes",
                            ParentId = 58L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 66L,
                            Color = "#ffffff",
                            Icon = "mdi-chart-line",
                            Name = "Investments",
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 67L,
                            Color = "#ffffff",
                            Icon = "mdi-image",
                            Name = "Collections",
                            ParentId = 66L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 68L,
                            Color = "#ffffff",
                            Icon = "mdi-chart-multiple",
                            Name = "Financial investments",
                            ParentId = 66L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 69L,
                            Color = "#ffffff",
                            Icon = "mdi-domain",
                            Name = "Realty",
                            ParentId = 66L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 70L,
                            Color = "#ffffff",
                            Icon = "mdi-account-cash",
                            Name = "Savings",
                            ParentId = 66L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 71L,
                            Color = "#ffffff",
                            Icon = "mdi-car",
                            Name = "Vehicles, chattels",
                            ParentId = 66L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 72L,
                            Color = "#ffffff",
                            Icon = "mdi-currency-usd",
                            Name = "Income",
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 73L,
                            Color = "#ffffff",
                            Icon = "mdi-newspaper",
                            Name = "Checks, coupons",
                            ParentId = 72L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 74L,
                            Color = "#ffffff",
                            Icon = "mdi-account-child",
                            Name = "Child Support",
                            ParentId = 72L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 75L,
                            Color = "#ffffff",
                            Icon = "mdi-check-decagram",
                            Name = "Dues & grants",
                            ParentId = 72L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 76L,
                            Color = "#ffffff",
                            Icon = "mdi-gift",
                            Name = "Gifts",
                            ParentId = 72L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 77L,
                            Color = "#ffffff",
                            Icon = "mdi-ticket-percent",
                            Name = "Interests, dividends",
                            ParentId = 72L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 78L,
                            Color = "#ffffff",
                            Icon = "mdi-currency-usd",
                            Name = "Lending, renting",
                            ParentId = 72L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 79L,
                            Color = "#ffffff",
                            Icon = "mdi-dice-5",
                            Name = "Lottery, gambling",
                            ParentId = 72L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 80L,
                            Color = "#ffffff",
                            Icon = "mdi-undo",
                            Name = "Refunds (tax, purchase)",
                            ParentId = 72L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 81L,
                            Color = "#ffffff",
                            Icon = "mdi-home",
                            Name = "Rental income",
                            ParentId = 72L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 82L,
                            Color = "#ffffff",
                            Icon = "mdi-sale",
                            Name = "Sale",
                            ParentId = 72L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 83L,
                            Color = "#ffffff",
                            Icon = "mdi-currency-usd",
                            Name = "Wage, invoices",
                            ParentId = 72L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 84L,
                            Color = "#ffffff",
                            Icon = "mdi-account-question",
                            Name = "Others",
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        },
                        new
                        {
                            Id = 85L,
                            Color = "#ffffff",
                            Icon = "mdi-help-circle",
                            Name = "Missing",
                            ParentId = 84L,
                            System = 0ul,
                            UserId = "b2beece6-28da-4c7f-b304-3a526d166f00"
                        });
                });

            modelBuilder.Entity("avarice_backend.Template", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("accountId");

                    b.Property<double>("Amount")
                        .HasColumnType("double")
                        .HasColumnName("amount");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("categoryId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double");

                    b.Property<long?>("TransferAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("transferAccountId");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("TransferAccountId");

                    b.HasIndex(new[] { "AccountId" }, "accountId");

                    b.HasIndex(new[] { "CategoryId" }, "categoryId");

                    b.HasIndex(new[] { "Latitude" }, "latitude");

                    b.HasIndex(new[] { "Longitude" }, "longitude");

                    b.HasIndex(new[] { "UserId" }, "userId")
                        .HasDatabaseName("userId1");

                    b.ToTable("template", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "latin1");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "latin1_swedish_ci");
                });

            modelBuilder.Entity("avarice_backend.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("accountId");

                    b.Property<double>("Amount")
                        .HasColumnType("double")
                        .HasColumnName("amount");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("categoryId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double")
                        .HasColumnName("longitude");

                    b.Property<long?>("TransferAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("transferAccountId");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("TransferAccountId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "AccountId" }, "accountId")
                        .HasDatabaseName("accountId1");

                    b.HasIndex(new[] { "CategoryId" }, "categoryId")
                        .HasDatabaseName("categoryId1");

                    b.ToTable("transaction", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "latin1");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "latin1_swedish_ci");
                });

            modelBuilder.Entity("avarice_backend.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b2beece6-28da-4c7f-b304-3a526d166f00",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "48ad95fa-743a-4673-8927-5044d96b7717",
                            Email = "mnovosel5@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MNOVOSEL5@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEHHZcifrXCQ1DciNISJi3aJgQJW+jyI+G66JPqVhhqfdn/wHXaXr8tQ0IK+F1iVJCw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "M5INRPR3EKT2FOPSOKK2PJZMR4A3AKYN",
                            TwoFactorEnabled = false,
                            UserName = "matija"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("avarice_backend.Account", b =>
                {
                    b.HasOne("avarice_backend.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .HasConstraintName("account_ibfk_1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("avarice_backend.Category", b =>
                {
                    b.HasOne("avarice_backend.Category", "Parent")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("category_ibfk_2");

                    b.HasOne("avarice_backend.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .HasConstraintName("category_ibfk_1");

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("avarice_backend.Template", b =>
                {
                    b.HasOne("avarice_backend.Account", "Account")
                        .WithMany("Templates")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("template_ibfk_1");

                    b.HasOne("avarice_backend.Category", "Category")
                        .WithMany("Templates")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("template_ibfk_4");

                    b.HasOne("avarice_backend.Account", "TransferAccount")
                        .WithMany("TransferTemplates")
                        .HasForeignKey("TransferAccountId")
                        .HasConstraintName("template_ibfk_2");

                    b.HasOne("avarice_backend.User", "User")
                        .WithMany("Templates")
                        .HasForeignKey("UserId")
                        .HasConstraintName("template_ibfk_3");

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("TransferAccount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("avarice_backend.Transaction", b =>
                {
                    b.HasOne("avarice_backend.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("transaction_ibfk_1");

                    b.HasOne("avarice_backend.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("transaction_ibfk_3");

                    b.HasOne("avarice_backend.Account", "TransferAccount")
                        .WithMany("TransferTransactions")
                        .HasForeignKey("TransferAccountId")
                        .HasConstraintName("transaction_ibfk_2");

                    b.HasOne("avarice_backend.User", null)
                        .WithMany("Transactions")
                        .HasForeignKey("UserId");

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("TransferAccount");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("avarice_backend.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("avarice_backend.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("avarice_backend.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("avarice_backend.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("avarice_backend.Account", b =>
                {
                    b.Navigation("Templates");

                    b.Navigation("Transactions");

                    b.Navigation("TransferTemplates");

                    b.Navigation("TransferTransactions");
                });

            modelBuilder.Entity("avarice_backend.Category", b =>
                {
                    b.Navigation("SubCategories");

                    b.Navigation("Templates");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("avarice_backend.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Categories");

                    b.Navigation("Templates");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
